### ISSUE TITLE
Page Up/Down keys do not work on Windows/macOS

### ISSUE THREAD

**Issue by xiaoqiangwang** [qterm/qterm#1]
No effect when pressing Page Up/Down on Windows or Fn+Up/Down on macOS.

**Comment by xiaoqiangwang** [comment]
I rebuilt under Qt 4.8 on macOS. The Fn+Up/Down keys are functional.

**Comment by xiaoqiangwang** [comment]
And on Windows under Qt 4.8, PageUp and PageDown keys are also functional. So this is definitely related to Qt 5.

**Comment by hephooey** [comment]
c06dba6b51f45b9dec9f92e9b506814f06b6a30e should have fixed the problem in Qt5, please test it.

**Comment by xiaoqiangwang** [comment]
Yes, the problem got fixed as tested under macOS and Qt 5.7.
