### ISSUE TITLE
Ubuntu unity界面下窗口菜单和系统的菜单重复了

### ISSUE THREAD

**Issue by RuralHunter** [qterm/qterm#11]
一般的程序是菜单只显示在unity窗口管理器上面，窗口自己不显示了。qterm自己的窗口还另外显示了一份，跟系统的重复了。

**Comment by hephooey** [comment]
这个应该是 ubuntu 自己的 appmenu-qt/appmenu-qt5 处理的，没法在 qterm 里面改

**Comment by xiaoqiangwang** [comment]
unity 已经被放弃了，
https://insights.ubuntu.com/2017/04/05/growing-ubuntu-for-cloud-and-iot-rather-than-phone-and-convergence/
