### ISSUE TITLE
Fwd:  [abrt] qterm: sig_fatal_handler(): QTerm killed by SIGABRT

### ISSUE THREAD

**Issue by cheese** [qterm/qterm#16]
https://bugzilla.redhat.com/show_bug.cgi?id=1529834

Description of problem:
Started Qterm
Stay disconnect from ant server
Click on BBS => Image Viewer
***CRASH***

Version-Release number of selected component:
qterm-0.7.1-1.fc26

Additional info:
reporter:       libreport-2.9.3
backtrace_rating: 4
cmdline:        QTerm -caption 'QTerm' --icon qterm
crash_function: sig_fatal_handler
executable:     /usr/bin/QTerm
journald_cursor: s=999870a87b584c2abeb145342a71b0d2;i=acf08;b=6aebf1b7fab54e4c814fdf4ad049033e;m=369e0015e9;t=561859033e740;x=da541645b07ca980
kernel:         4.14.6-300.fc27.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000

**Comment by xiaoqiangwang** [comment]
Fixed in 7e8c5c4.
