### ISSUE TITLE
MacOS retina solution has not been support

### ISSUE THREAD

**Issue by tao-bioinfo** [qterm/qterm#19]
Currently I manually edit the `Info.plist` file and add:
```
       <key>NSHighResolutionCapable</key>
       <true/>
```
Then it would be fixed

**Comment by xiaoqiangwang** [comment]
Thanks for report. It should be fixed in commit aac6aa521fc71b220dfc3cd74f522731fe099fb5. I don't own a retina macOS device to check though.
