### ISSUE TITLE
ssh下连接设置->终端里的行数无效

### ISSUE THREAD

**Issue by RuralHunter** [qterm/qterm#2]
同一个站点（水木社区），选telnet就有用，选ssh就没有用。

**Comment by xiaoqiangwang** [comment]
从这里看现在是写死的， @hephooey 可能当时还没时间 ;)
https://github.com/qterm/qterm/blob/master/src/ssh/channel.cpp#L178

**Comment by hephooey** [comment]
@RuralHunter, see the commit above, should be fixed, please test.

**Comment by RuralHunter** [comment]
I confirm it's fixed. Thanks!
