### ISSUE TITLE
Cannot connect to bdwm.net aka bbs.pku.edu.cn

### ISSUE THREAD

**Issue by hyiltiz** [qterm/qterm#21]
Simply doing `ssh guest@bdwm.net` will successfully connect, but I was unable to configure QTerm such that it could connect to `bdwm.net`. None of the combinations of the following settings helped:
- SSH over port 22
- telnet over port 23,
- with and without automatic logins
- changing and not changing 
- using bbs.pku.edu.cn or bdwm.net

How should I set up QTerm such that it could connect? I used to be able to connect to this site with QTerm (about five years ago).

QTerm versions: `QTerm 0.7.3 (Qt 5.12.5 based)`
OS: Debian testing, aka `Linux version 5.4.0-3-amd64 (debian-kernel@lists.debian.org) (gcc version 9.2.1 20200117 (Debian 9.2.1-24)) #1 SMP Debian 5.4.13-1 (2020-01-19)`

**Comment by xiaoqiangwang** [comment]
This is what I observed.

For the first time connections, qterm will ask for you to add host key but will time out. Now just press enter, it will reconnect and prompt for user name and password.

Would that work for you as well?

**Comment by hyiltiz** [comment]
Yes, that was the behavior. I tried inputting my username and password after pressing enter and during the reconnect, but after than nothing happened and got a black screen. Not sure if I tried `Guest` as the username.

**Comment by xiaoqiangwang** [comment]
I can reproduce the problem: nothing is displayed after login with guest:guest but it has the connection to the server and it sends keystrokes as well.
