### ISSUE TITLE
无法设置自动登录 水木社区

### ISSUE THREAD

**Issue by atzlinux** [qterm/qterm#26]
bbs.newsmth.net

设置自动登录账号后，不生效，每次还是停在：

请输入代号:

**Comment by xiaoqiangwang** [comment]
SSH 链接的用户名密码设置在 SSH Tab
![qterm_settings_ssh](https://user-images.githubusercontent.com/3283924/94429118-20148200-0192-11eb-9f91-1d73128f10a2.png)
