### ISSUE TITLE
Unknown private key type, don't support OpenSSH private key rsa

### ISSUE THREAD

**Issue by atzlinux** [qterm/qterm#38]
Hi,
 When I use ~/.ssh/id_rsa connect to BSS bbs.mysmth.net,

I get the error info in cosole: 

key size:  256
Verify RSA:  1
Unknown private key type

Please add support for rsa ssh private key.

Thanks!

**Comment by atzlinux** [comment]
After use this command convert the private key to old PEM format:
ssh-keygen -e -f id_rsa -m PEM > id_rsa.PEM

head -n 2 id_rsa.PEM 
-----BEGIN RSA PUBLIC KEY-----
MIIBigKCAYE.............ySH6AmfbmZ+1as1
.......

This bug still exist.

**Comment by atzlinux** [comment]
qterm only support old ssh version 1 ssh1 key.

apt-get install openssh-client-ssh1

then run:

ssh-keygen1

to get ssh1 key.

**Comment by xiaoqiangwang** [comment]
0..8.2 adds support of PKCS#8 key files., https://en.wikipedia.org/wiki/PKCS_8
$ ssh-keygen -t rsa -m PKCS8  -f id_rsa

The openssh format , with banner "-----BEGIN OPENSSH PRIVATE KEY-----", is not supported.
