### ISSUE TITLE
address book config window too large

### ISSUE THREAD

**Issue by yankaiqian** [qterm/qterm#5]
QTerm 0.7.0 (Qt 4.8.7 based)
my screen resolution: 1366x768

The height of address book config window is larger than current height of screen, I could not see the buttons  in bottom.

Please help to look into this, thanks!

**Comment by xiaoqiangwang** [comment]
@hephooey Is this extra large dialog required on HiDPI screens?

**Comment by hephooey** [comment]
I think we can shrink the height to fit into 768 pixels. But it seems I need to break the layout and rearrange them. I probably will try it this weekend.

**Comment by hephooey** [comment]
I committed 007b51e2a79848ace041a245685967dd18eff6c6 yesterday, the addressbook window now starts from 830x720 if the size is not specified in the config files. Please test if it is good enough. You might need to delete the old config file for the change to take effect. If this still does not work, we probably should prepare two ui files and load them according to the dpi detected.

**Comment by xiaoqiangwang** [comment]
It fits on my 1440x900. It seems hard to convince the layout engine to shrink even more.

**Comment by yankaiqian** [comment]
Thanks for the update, but I have a new issue about the the address book, I can not adjust the size of left frame, it's not easy to browse the address directory tree.

I am using qterm 0.7.2-1 on debian linux, please find the capture below.

![qterm_0 7 2_addr_config_window](https://user-images.githubusercontent.com/3888149/32405609-979305cc-c1a3-11e7-8a41-f28f27e9207f.png)
