### ISSUE TITLE
Updating package in Debian

### ISSUE THREAD

**Issue by hosiet** [qterm/qterm#6]
Glad to see that a new upstream has picked up the qterm software. Looks like we could try to update the qterm package in Debian.

Before we start the work, there are several questions:

* Does new qterm support openssl 1.1.0?
* Could you please tag another release against Git HEAD (or point out any commit that is considered stable) to ease the work of packaging?

Thanks!

**Comment by xiaoqiangwang** [comment]
The current HEAD has openssl 1.1.0 support. @hephooey needs to address issue #5, and then it would be ready for a new release.

**Comment by xiaoqiangwang** [comment]
0.7.1 has been tagged. Thanks for taking care of the debian package.
