### ISSUE TITLE
Licensing conflict: GPL2+ vs. OpenSSL

### ISSUE THREAD

**Issue by hosiet** [qterm/qterm#7]
During the packaging of qterm for Debian, I noticed that your code was linked against openssl but the whole code is licensed under GPL2+. Those two licenses are not compatible.

For more information, please refer to https://lintian.debian.org/tags/possible-gpl-code-linked-with-openssl.html.

Please consider adding an exception for openssl in the license [1] [2], or provide with an alternative crypto library interface (e.g., mbedTLS, gnutls, etc).

[1] https://people.gnome.org/~markmc/openssl-and-the-gpl
[2] https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

**Comment by hosiet** [comment]
The freeze for Debian 9 is approaching. If the issue is not solved before 2017-01-05, then qterm won't be able to enter Debian 9 anymore.

**Comment by hephooey** [comment]
Submitted a PR containing the license exception, @xiaoqiangwang could you review and merge it if you are OK with the change?

**Comment by xiaoqiangwang** [comment]
I have merged the license update. @hosiet the license exception wording is taken from your suggested link [1]. Thank you for maintaining the Debian package.

**Comment by hosiet** [comment]
Looks great. Thanks!
