### ISSUE TITLE
Build error on Debian stretch (QT_QCOLLECTIONGENERATOR_EXECUTABLE-NOTFOUND)

### ISSUE THREAD

**Issue by yankaiqian** [qterm/qterm#9]
Not a bug, just share this to others.

You may got the error below when build it on Debian stretch with QT4, and you had installed qt4-dev-tools already:

> [  1%] Automatic moc for target qterm
[  1%] Built target qterm_automoc
[  3%] Built target translations_target
[  4%] Compiling Qt help collection project qterm.qhcp
/bin/sh: 1: QT_QCOLLECTIONGENERATOR_EXECUTABLE-NOTFOUND: not found
src/doc/CMakeFiles/help_target.dir/build.make:61: recipe for target 'src/doc/qterm.qhc' failed
make[2]: *** [src/doc/qterm.qhc] Error 127
CMakeFiles/Makefile2:1239: recipe for target 'src/doc/CMakeFiles/help_target.dir/all' failed
make[1]: *** [src/doc/CMakeFiles/help_target.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

How to solve? you need to specify it:
`cmake ../qterm-0.7.1 -DQT_QCOLLECTIONGENERATOR_EXECUTABLE=/usr/lib/x86_64-linux-gnu/qt4/bin/qcollectiongenerator`

**Comment by hosiet** [comment]
No need to hack around. The env `QT_SELECT` can help solve all those problems.
